######################################################################
# Automatically generated by qmake (2.01a) ? 9? 21 15:49:36 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageexpansion.h
FORMS += imageexpansion.ui
SOURCES += imageexpansion.cpp main.cpp
